
api = 'https://chatixapi.herokuapp.com/'
sendMessageApi = 'postMessage'
getMessageApi = 'getMessage'
updateBackgroundApi = 'updateBackground'
clearChatApi = 'clearChat'
ViewModeApi = 'onlyViewMode'
getJsonChatApi = 'getJson'
sendFileUrlApi = 'sendFileUrl'
sendFileApi = 'sendFile'
getUidApi = 'getUid'
BanApi = 'banUser'
unBanApi = 'unbanUser'
